// DONTCOVER
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: archway/rewards/v1beta1/rewards.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the module parameters.
type Params struct {
	// inflation_rewards_ratio defines the percentage of minted inflation tokens
	// that are used for dApp rewards [0.0, 1.0]. If set to 0.0, no inflation
	// rewards are distributed.
	InflationRewardsRatio github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=inflation_rewards_ratio,json=inflationRewardsRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"inflation_rewards_ratio"`
	// tx_fee_rebate_ratio defines the percentage of tx fees that are used for
	// dApp rewards [0.0, 1.0]. If set to 0.0, no fee rewards are distributed.
	TxFeeRebateRatio github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=tx_fee_rebate_ratio,json=txFeeRebateRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"tx_fee_rebate_ratio"`
	// max_withdraw_records defines the maximum number of RewardsRecord objects
	// used for the withdrawal operation.
	MaxWithdrawRecords uint64 `protobuf:"varint,3,opt,name=max_withdraw_records,json=maxWithdrawRecords,proto3" json:"max_withdraw_records,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f478faffe74434, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxWithdrawRecords() uint64 {
	if m != nil {
		return m.MaxWithdrawRecords
	}
	return 0
}

// ContractMetadata defines the contract rewards distribution options for a
// particular contract.
type ContractMetadata struct {
	// contract_address defines the contract address (bech32 encoded).
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// owner_address is the contract owner address that can modify contract reward
	// options (bech32 encoded). That could be the contract admin or the contract
	// itself. If owner_address is set to contract address, contract can modify
	// the metadata on its own using WASM bindings.
	OwnerAddress string `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	// rewards_address is an address to distribute rewards to (bech32 encoded).
	// If not set (empty), rewards are not distributed for this contract.
	RewardsAddress                    string `protobuf:"bytes,3,opt,name=rewards_address,json=rewardsAddress,proto3" json:"rewards_address,omitempty"`
	MinimumRewardAmount               uint64 `protobuf:"varint,4,opt,name=minimum_reward_amount,json=minimumRewardAmount,proto3" json:"minimum_reward_amount,omitempty"`
	LiquidityTokenAddress             string `protobuf:"bytes,5,opt,name=liquidity_token_address,json=liquidityTokenAddress,proto3" json:"liquidity_token_address,omitempty"`
	LiquidStakeInterval               uint64 `protobuf:"varint,6,opt,name=liquid_stake_interval,json=liquidStakeInterval,proto3" json:"liquid_stake_interval,omitempty"`
	RedemptionInterval                uint64 `protobuf:"varint,7,opt,name=redemption_interval,json=redemptionInterval,proto3" json:"redemption_interval,omitempty"`
	RewardsWithdrawalInterval         uint64 `protobuf:"varint,8,opt,name=rewards_withdrawal_interval,json=rewardsWithdrawalInterval,proto3" json:"rewards_withdrawal_interval,omitempty"`
	RedemptionAddress                 string `protobuf:"bytes,9,opt,name=redemption_address,json=redemptionAddress,proto3" json:"redemption_address,omitempty"`
	RedemptionRateThreshold           uint64 `protobuf:"varint,10,opt,name=redemption_rate_threshold,json=redemptionRateThreshold,proto3" json:"redemption_rate_threshold,omitempty"`
	RedemptionIntervalThreshold       uint64 `protobuf:"varint,11,opt,name=redemption_interval_threshold,json=redemptionIntervalThreshold,proto3" json:"redemption_interval_threshold,omitempty"`
	MaximumThreshold                  uint64 `protobuf:"varint,12,opt,name=maximum_threshold,json=maximumThreshold,proto3" json:"maximum_threshold,omitempty"`
	ArchwayRewardFundsTransferAddress string `protobuf:"bytes,13,opt,name=archway_reward_funds_transfer_address,json=archwayRewardFundsTransferAddress,proto3" json:"archway_reward_funds_transfer_address,omitempty"`
	LiquidityProviderAddress          string `protobuf:"bytes,14,opt,name=liquidity_provider_address,json=liquidityProviderAddress,proto3" json:"liquidity_provider_address,omitempty"`
	LiquidityProviderCommission       uint64 `protobuf:"varint,15,opt,name=liquidity_provider_commission,json=liquidityProviderCommission,proto3" json:"liquidity_provider_commission,omitempty"`
	AirdropDuration                   uint64 `protobuf:"varint,16,opt,name=airdrop_duration,json=airdropDuration,proto3" json:"airdrop_duration,omitempty"`
	AirdropRecipientAddress           string `protobuf:"bytes,17,opt,name=airdrop_recipient_address,json=airdropRecipientAddress,proto3" json:"airdrop_recipient_address,omitempty"`
	AirdropVestingPeriod              uint64 `protobuf:"varint,18,opt,name=airdrop_vesting_period,json=airdropVestingPeriod,proto3" json:"airdrop_vesting_period,omitempty"`
}

func (m *ContractMetadata) Reset()      { *m = ContractMetadata{} }
func (*ContractMetadata) ProtoMessage() {}
func (*ContractMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f478faffe74434, []int{1}
}
func (m *ContractMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContractMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContractMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContractMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractMetadata.Merge(m, src)
}
func (m *ContractMetadata) XXX_Size() int {
	return m.Size()
}
func (m *ContractMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ContractMetadata proto.InternalMessageInfo

func (m *ContractMetadata) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *ContractMetadata) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *ContractMetadata) GetRewardsAddress() string {
	if m != nil {
		return m.RewardsAddress
	}
	return ""
}

func (m *ContractMetadata) GetMinimumRewardAmount() uint64 {
	if m != nil {
		return m.MinimumRewardAmount
	}
	return 0
}

func (m *ContractMetadata) GetLiquidityTokenAddress() string {
	if m != nil {
		return m.LiquidityTokenAddress
	}
	return ""
}

func (m *ContractMetadata) GetLiquidStakeInterval() uint64 {
	if m != nil {
		return m.LiquidStakeInterval
	}
	return 0
}

func (m *ContractMetadata) GetRedemptionInterval() uint64 {
	if m != nil {
		return m.RedemptionInterval
	}
	return 0
}

func (m *ContractMetadata) GetRewardsWithdrawalInterval() uint64 {
	if m != nil {
		return m.RewardsWithdrawalInterval
	}
	return 0
}

func (m *ContractMetadata) GetRedemptionAddress() string {
	if m != nil {
		return m.RedemptionAddress
	}
	return ""
}

func (m *ContractMetadata) GetRedemptionRateThreshold() uint64 {
	if m != nil {
		return m.RedemptionRateThreshold
	}
	return 0
}

func (m *ContractMetadata) GetRedemptionIntervalThreshold() uint64 {
	if m != nil {
		return m.RedemptionIntervalThreshold
	}
	return 0
}

func (m *ContractMetadata) GetMaximumThreshold() uint64 {
	if m != nil {
		return m.MaximumThreshold
	}
	return 0
}

func (m *ContractMetadata) GetArchwayRewardFundsTransferAddress() string {
	if m != nil {
		return m.ArchwayRewardFundsTransferAddress
	}
	return ""
}

func (m *ContractMetadata) GetLiquidityProviderAddress() string {
	if m != nil {
		return m.LiquidityProviderAddress
	}
	return ""
}

func (m *ContractMetadata) GetLiquidityProviderCommission() uint64 {
	if m != nil {
		return m.LiquidityProviderCommission
	}
	return 0
}

func (m *ContractMetadata) GetAirdropDuration() uint64 {
	if m != nil {
		return m.AirdropDuration
	}
	return 0
}

func (m *ContractMetadata) GetAirdropRecipientAddress() string {
	if m != nil {
		return m.AirdropRecipientAddress
	}
	return ""
}

func (m *ContractMetadata) GetAirdropVestingPeriod() uint64 {
	if m != nil {
		return m.AirdropVestingPeriod
	}
	return 0
}

// BlockRewards defines block related rewards distribution data.
type BlockRewards struct {
	// height defines the block height.
	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// inflation_rewards is the rewards to be distributed.
	InflationRewards types.Coin `protobuf:"bytes,2,opt,name=inflation_rewards,json=inflationRewards,proto3" json:"inflation_rewards"`
	// max_gas defines the maximum gas for the block that is used to distribute
	// inflation rewards (consensus parameter).
	MaxGas uint64 `protobuf:"varint,3,opt,name=max_gas,json=maxGas,proto3" json:"max_gas,omitempty"`
}

func (m *BlockRewards) Reset()      { *m = BlockRewards{} }
func (*BlockRewards) ProtoMessage() {}
func (*BlockRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f478faffe74434, []int{2}
}
func (m *BlockRewards) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockRewards.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRewards.Merge(m, src)
}
func (m *BlockRewards) XXX_Size() int {
	return m.Size()
}
func (m *BlockRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRewards.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRewards proto.InternalMessageInfo

func (m *BlockRewards) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockRewards) GetInflationRewards() types.Coin {
	if m != nil {
		return m.InflationRewards
	}
	return types.Coin{}
}

func (m *BlockRewards) GetMaxGas() uint64 {
	if m != nil {
		return m.MaxGas
	}
	return 0
}

// TxRewards defines transaction related rewards distribution data.
type TxRewards struct {
	// tx_id is the tracking transaction ID (x/tracking is the data source for
	// this value).
	TxId uint64 `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// height defines the block height.
	Height int64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// fee_rewards is the rewards to be distributed.
	FeeRewards []types.Coin `protobuf:"bytes,3,rep,name=fee_rewards,json=feeRewards,proto3" json:"fee_rewards"`
}

func (m *TxRewards) Reset()      { *m = TxRewards{} }
func (*TxRewards) ProtoMessage() {}
func (*TxRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f478faffe74434, []int{3}
}
func (m *TxRewards) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxRewards.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRewards.Merge(m, src)
}
func (m *TxRewards) XXX_Size() int {
	return m.Size()
}
func (m *TxRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRewards.DiscardUnknown(m)
}

var xxx_messageInfo_TxRewards proto.InternalMessageInfo

func (m *TxRewards) GetTxId() uint64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

func (m *TxRewards) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TxRewards) GetFeeRewards() []types.Coin {
	if m != nil {
		return m.FeeRewards
	}
	return nil
}

// RewardsRecord defines a record that is used to distribute rewards later (lazy
// distribution). This record is being created by the x/rewards EndBlocker and
// pruned after the rewards are distributed. An actual rewards x/bank transfer
// might be triggered by a Tx (via CLI for example) or by a contract via WASM
// bindings. For a contract to trigger rewards transfer, contract address must
// be set as the rewards_address in a corresponding ContractMetadata.
type RewardsRecord struct {
	// id is the unique ID of the record.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// rewards_address is the address to distribute rewards to (bech32 encoded).
	RewardsAddress string `protobuf:"bytes,2,opt,name=rewards_address,json=rewardsAddress,proto3" json:"rewards_address,omitempty"`
	// rewards are the rewards to be transferred later.
	Rewards []types.Coin `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards"`
	// calculated_height defines the block height of rewards calculation event.
	CalculatedHeight int64 `protobuf:"varint,4,opt,name=calculated_height,json=calculatedHeight,proto3" json:"calculated_height,omitempty"`
	// calculated_time defines the block time of rewards calculation event.
	CalculatedTime time.Time `protobuf:"bytes,5,opt,name=calculated_time,json=calculatedTime,proto3,stdtime" json:"calculated_time"`
}

func (m *RewardsRecord) Reset()      { *m = RewardsRecord{} }
func (*RewardsRecord) ProtoMessage() {}
func (*RewardsRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f478faffe74434, []int{4}
}
func (m *RewardsRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardsRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardsRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardsRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardsRecord.Merge(m, src)
}
func (m *RewardsRecord) XXX_Size() int {
	return m.Size()
}
func (m *RewardsRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardsRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RewardsRecord proto.InternalMessageInfo

func (m *RewardsRecord) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RewardsRecord) GetRewardsAddress() string {
	if m != nil {
		return m.RewardsAddress
	}
	return ""
}

func (m *RewardsRecord) GetRewards() []types.Coin {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *RewardsRecord) GetCalculatedHeight() int64 {
	if m != nil {
		return m.CalculatedHeight
	}
	return 0
}

func (m *RewardsRecord) GetCalculatedTime() time.Time {
	if m != nil {
		return m.CalculatedTime
	}
	return time.Time{}
}

// FlatFee defines the flat fee for a particular contract.
type FlatFee struct {
	// contract_address defines the contract address (bech32 encoded).
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// flat_fee defines the minimum flat fee set by the contract_owner
	FlatFee types.Coin `protobuf:"bytes,2,opt,name=flat_fee,json=flatFee,proto3" json:"flat_fee"`
}

func (m *FlatFee) Reset()      { *m = FlatFee{} }
func (*FlatFee) ProtoMessage() {}
func (*FlatFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f478faffe74434, []int{5}
}
func (m *FlatFee) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FlatFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FlatFee.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FlatFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlatFee.Merge(m, src)
}
func (m *FlatFee) XXX_Size() int {
	return m.Size()
}
func (m *FlatFee) XXX_DiscardUnknown() {
	xxx_messageInfo_FlatFee.DiscardUnknown(m)
}

var xxx_messageInfo_FlatFee proto.InternalMessageInfo

func (m *FlatFee) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *FlatFee) GetFlatFee() types.Coin {
	if m != nil {
		return m.FlatFee
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Params)(nil), "archway.rewards.v1beta1.Params")
	proto.RegisterType((*ContractMetadata)(nil), "archway.rewards.v1beta1.ContractMetadata")
	proto.RegisterType((*BlockRewards)(nil), "archway.rewards.v1beta1.BlockRewards")
	proto.RegisterType((*TxRewards)(nil), "archway.rewards.v1beta1.TxRewards")
	proto.RegisterType((*RewardsRecord)(nil), "archway.rewards.v1beta1.RewardsRecord")
	proto.RegisterType((*FlatFee)(nil), "archway.rewards.v1beta1.FlatFee")
}

func init() {
	proto.RegisterFile("archway/rewards/v1beta1/rewards.proto", fileDescriptor_50f478faffe74434)
}

var fileDescriptor_50f478faffe74434 = []byte{
	// 983 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0x8e, 0x3f, 0x6a, 0x27, 0x93, 0x0f, 0x3b, 0x9b, 0xa4, 0xde, 0xa4, 0xaa, 0x1d, 0x8a, 0x80,
	0x22, 0x94, 0x5d, 0x1a, 0x10, 0x12, 0x11, 0x42, 0xd4, 0xa9, 0x02, 0x95, 0x5a, 0x29, 0x5a, 0x2c,
	0x2a, 0x21, 0xa1, 0xd5, 0x78, 0x67, 0x6c, 0x8f, 0xbc, 0xbb, 0x63, 0x66, 0xc6, 0xf6, 0xe6, 0xc6,
	0x05, 0x71, 0xad, 0xc4, 0x85, 0x23, 0x3f, 0xa7, 0xc7, 0x1e, 0x11, 0x87, 0x82, 0x92, 0x1f, 0xc0,
	0x5f, 0x40, 0xf3, 0xb5, 0xbb, 0x90, 0x1c, 0xda, 0x9e, 0xec, 0x79, 0x9f, 0xe7, 0xfd, 0x9a, 0x8f,
	0xe7, 0x5d, 0xf0, 0x1e, 0x64, 0xd1, 0x64, 0x09, 0x2f, 0x7c, 0x86, 0x97, 0x90, 0x21, 0xee, 0x2f,
	0x1e, 0x0c, 0xb1, 0x80, 0x0f, 0xec, 0xda, 0x9b, 0x31, 0x2a, 0xa8, 0xd3, 0x31, 0x34, 0xcf, 0x9a,
	0x0d, 0xed, 0x60, 0x77, 0x4c, 0xc7, 0x54, 0x71, 0x7c, 0xf9, 0x4f, 0xd3, 0x0f, 0x7a, 0x63, 0x4a,
	0xc7, 0x31, 0xf6, 0xd5, 0x6a, 0x38, 0x1f, 0xf9, 0x82, 0x24, 0x98, 0x0b, 0x98, 0xcc, 0x0c, 0xa1,
	0x1b, 0x51, 0x9e, 0x50, 0xee, 0x0f, 0x21, 0xc7, 0x79, 0xca, 0x88, 0x92, 0x54, 0xe3, 0xf7, 0x7e,
	0xa9, 0x82, 0xc6, 0x39, 0x64, 0x30, 0xe1, 0xce, 0x08, 0x74, 0x48, 0x3a, 0x8a, 0xa1, 0x20, 0x34,
	0x0d, 0x4d, 0xfa, 0x90, 0xc9, 0xa5, 0x5b, 0x39, 0xac, 0xdc, 0x5f, 0xeb, 0x7b, 0x2f, 0x5e, 0xf5,
	0x56, 0xfe, 0x7c, 0xd5, 0x7b, 0x7f, 0x4c, 0xc4, 0x64, 0x3e, 0xf4, 0x22, 0x9a, 0xf8, 0x26, 0xbc,
	0xfe, 0x39, 0xe2, 0x68, 0xea, 0x8b, 0x8b, 0x19, 0xe6, 0xde, 0x23, 0x1c, 0x05, 0x7b, 0x79, 0xb8,
	0x40, 0x47, 0x0b, 0xe4, 0xc2, 0xf9, 0x01, 0xec, 0x88, 0x2c, 0x1c, 0x61, 0x1c, 0x32, 0x3c, 0x84,
	0x02, 0x9b, 0x1c, 0xd5, 0xb7, 0xca, 0xd1, 0x16, 0xd9, 0x19, 0xc6, 0x81, 0x0a, 0xa4, 0xc3, 0x7f,
	0x0c, 0x76, 0x13, 0x98, 0x85, 0x4b, 0x22, 0x26, 0x88, 0xc1, 0x65, 0xc8, 0x70, 0x44, 0x19, 0xe2,
	0x6e, 0xed, 0xb0, 0x72, 0xbf, 0x1e, 0x38, 0x09, 0xcc, 0x9e, 0x19, 0x28, 0xd0, 0xc8, 0x49, 0xfd,
	0xb7, 0xdf, 0x7b, 0x2b, 0xf7, 0xfe, 0x69, 0x82, 0xf6, 0x29, 0x4d, 0x05, 0x83, 0x91, 0x78, 0x8a,
	0x05, 0x44, 0x50, 0x40, 0xe7, 0x43, 0xd0, 0x8e, 0x8c, 0x2d, 0x84, 0x08, 0x31, 0xcc, 0xb9, 0xde,
	0x8c, 0xa0, 0x65, 0xed, 0x0f, 0xb5, 0xd9, 0x79, 0x17, 0x6c, 0xd2, 0x65, 0x8a, 0x59, 0xce, 0x53,
	0x0d, 0x05, 0x1b, 0xca, 0x68, 0x49, 0x1f, 0x80, 0x96, 0xdd, 0x59, 0x4b, 0xab, 0x29, 0xda, 0x96,
	0x31, 0x5b, 0xe2, 0x31, 0xd8, 0x4b, 0x48, 0x4a, 0x92, 0x79, 0x62, 0x8e, 0x22, 0x84, 0x09, 0x9d,
	0xa7, 0xc2, 0xad, 0xab, 0x36, 0x76, 0x0c, 0xa8, 0x37, 0xf6, 0xa1, 0x82, 0x9c, 0xcf, 0x40, 0x27,
	0x26, 0x3f, 0xce, 0x09, 0x22, 0xe2, 0x22, 0x14, 0x74, 0x8a, 0xd3, 0x3c, 0xc9, 0x2d, 0x95, 0x64,
	0x2f, 0x87, 0x07, 0x12, 0x2d, 0xe5, 0xd2, 0x40, 0xc8, 0x05, 0x9c, 0xe2, 0x90, 0xa4, 0x02, 0xb3,
	0x05, 0x8c, 0xdd, 0x86, 0xce, 0xa5, 0xc1, 0x6f, 0x25, 0xf6, 0xd8, 0x40, 0x8e, 0x0f, 0x76, 0x18,
	0x46, 0x38, 0x99, 0xa9, 0xdb, 0x92, 0x7b, 0x34, 0xf5, 0x26, 0x17, 0x50, 0xee, 0xf0, 0x25, 0xb8,
	0x63, 0x3b, 0xb7, 0x47, 0x03, 0xe3, 0xc2, 0x71, 0x55, 0x39, 0xee, 0x1b, 0xca, 0xb3, 0x9c, 0x91,
	0xfb, 0x1f, 0x81, 0x52, 0xd4, 0xbc, 0xaf, 0x35, 0xd5, 0xd7, 0x76, 0x81, 0xd8, 0x9e, 0x4e, 0xc0,
	0x7e, 0x89, 0xce, 0xe4, 0x35, 0x13, 0x13, 0x86, 0xf9, 0x84, 0xc6, 0xc8, 0x05, 0x2a, 0x59, 0xa7,
	0x20, 0x04, 0x50, 0xe0, 0x81, 0x85, 0x9d, 0x3e, 0xb8, 0x7b, 0x43, 0x6f, 0x25, 0xff, 0x75, 0xe5,
	0x7f, 0xe7, 0x7a, 0x97, 0x45, 0x8c, 0x8f, 0xc0, 0x76, 0x02, 0x33, 0x75, 0x7e, 0x85, 0xdf, 0x86,
	0xf2, 0x6b, 0x1b, 0xa0, 0x20, 0x9f, 0xe7, 0xea, 0x60, 0x0f, 0x7b, 0x34, 0x4f, 0x11, 0x0f, 0x05,
	0x83, 0x29, 0x1f, 0x95, 0xae, 0xd4, 0xa6, 0x6a, 0xf7, 0x1d, 0x43, 0xd6, 0x87, 0x7f, 0x26, 0xa9,
	0x03, 0xc3, 0xb4, 0xed, 0x7f, 0x01, 0x0e, 0x8a, 0xab, 0x30, 0x63, 0x74, 0x41, 0x50, 0x29, 0xcc,
	0x96, 0x0a, 0xe3, 0xe6, 0x8c, 0x73, 0x43, 0xb0, 0xde, 0x7d, 0x70, 0xf7, 0x06, 0xef, 0x88, 0x26,
	0x09, 0xe1, 0x9c, 0xd0, 0xd4, 0x6d, 0xe9, 0x0d, 0xb8, 0x16, 0xe0, 0x34, 0xa7, 0xc8, 0x97, 0x03,
	0x09, 0x43, 0x8c, 0xce, 0x42, 0x34, 0x57, 0x2f, 0x3c, 0x75, 0xdb, 0xca, 0xad, 0x65, 0xec, 0x8f,
	0x8c, 0x59, 0x9e, 0x95, 0xa5, 0x32, 0x1c, 0x91, 0x19, 0xc1, 0x69, 0xf1, 0xda, 0xb6, 0x55, 0xad,
	0x1d, 0x43, 0x08, 0x2c, 0x6e, 0x4b, 0xfd, 0x14, 0xdc, 0xb6, 0xbe, 0x0b, 0xcc, 0x05, 0x49, 0xc7,
	0xe1, 0x0c, 0x33, 0x42, 0x91, 0xeb, 0xa8, 0x64, 0xbb, 0x06, 0xfd, 0x4e, 0x83, 0xe7, 0x0a, 0x33,
	0x2f, 0xfe, 0xd7, 0x0a, 0xd8, 0xe8, 0xc7, 0x34, 0x9a, 0x1a, 0x79, 0x72, 0x6e, 0x83, 0xc6, 0x04,
	0x93, 0xf1, 0x44, 0xa8, 0x37, 0x5e, 0x0b, 0xcc, 0xca, 0x79, 0x02, 0xb6, 0xaf, 0x29, 0xa3, 0x7a,
	0xde, 0xeb, 0xc7, 0xfb, 0x9e, 0x96, 0x25, 0x4f, 0x0a, 0xac, 0x15, 0x6b, 0xef, 0x94, 0x92, 0xb4,
	0x5f, 0x97, 0x52, 0x16, 0xb4, 0xff, 0x2f, 0x82, 0x4e, 0x07, 0x34, 0xa5, 0x40, 0x8d, 0xa1, 0xd5,
	0xa4, 0x46, 0x02, 0xb3, 0xaf, 0xa1, 0xd5, 0xa1, 0x9f, 0x2a, 0x60, 0x6d, 0x90, 0x59, 0xf2, 0x0e,
	0xb8, 0x25, 0xb2, 0x90, 0x20, 0x55, 0x51, 0x3d, 0xa8, 0x8b, 0xec, 0x31, 0x2a, 0xd5, 0x59, 0xfd,
	0x4f, 0x9d, 0x5f, 0x81, 0x75, 0x2d, 0xab, 0xba, 0xc2, 0xda, 0x61, 0xed, 0x75, 0x2a, 0x04, 0x23,
	0x29, 0xa0, 0xca, 0xc5, 0x94, 0xf0, 0x73, 0x15, 0x6c, 0x5a, 0xc9, 0x56, 0x1a, 0xe9, 0x6c, 0x81,
	0x6a, 0x5e, 0x43, 0x95, 0xa0, 0x9b, 0x74, 0xac, 0x7a, 0xa3, 0x8e, 0x7d, 0x0e, 0x9a, 0x6f, 0x58,
	0x8e, 0xe5, 0xcb, 0x27, 0x14, 0xc1, 0x38, 0x9a, 0xc7, 0x50, 0x60, 0x14, 0x9a, 0x86, 0xeb, 0xaa,
	0xe1, 0x76, 0x01, 0x7c, 0xa3, 0x5b, 0x7f, 0x0a, 0x5a, 0x25, 0xb2, 0x9c, 0x82, 0x4a, 0xf3, 0xd6,
	0x8f, 0x0f, 0x3c, 0x3d, 0x22, 0x3d, 0x3b, 0x22, 0xbd, 0x81, 0x1d, 0x91, 0xfd, 0x55, 0x99, 0xf0,
	0xf9, 0x5f, 0xbd, 0x4a, 0xb0, 0x55, 0x38, 0x4b, 0xd8, 0xec, 0xc3, 0x02, 0x34, 0xcf, 0x62, 0x28,
	0xce, 0x30, 0x7e, 0x93, 0x41, 0x70, 0x02, 0x56, 0xe5, 0x89, 0xcb, 0x09, 0xf7, 0xba, 0x97, 0xa4,
	0x39, 0xd2, 0x69, 0x74, 0xde, 0xfe, 0x93, 0x17, 0x97, 0xdd, 0xca, 0xcb, 0xcb, 0x6e, 0xe5, 0xef,
	0xcb, 0x6e, 0xe5, 0xf9, 0x55, 0x77, 0xe5, 0xe5, 0x55, 0x77, 0xe5, 0x8f, 0xab, 0xee, 0xca, 0xf7,
	0xc7, 0xa5, 0xb1, 0x68, 0x54, 0xe0, 0x28, 0xc5, 0x62, 0x49, 0xd9, 0xd4, 0xae, 0xfd, 0x2c, 0xff,
	0xc4, 0x50, 0x63, 0x72, 0xd8, 0x50, 0x9d, 0x7f, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c,
	0xfc, 0xb8, 0xfb, 0x82, 0x08, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxWithdrawRecords != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.MaxWithdrawRecords))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.TxFeeRebateRatio.Size()
		i -= size
		if _, err := m.TxFeeRebateRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRewards(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.InflationRewardsRatio.Size()
		i -= size
		if _, err := m.InflationRewardsRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRewards(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ContractMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContractMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContractMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AirdropVestingPeriod != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.AirdropVestingPeriod))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if len(m.AirdropRecipientAddress) > 0 {
		i -= len(m.AirdropRecipientAddress)
		copy(dAtA[i:], m.AirdropRecipientAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.AirdropRecipientAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.AirdropDuration != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.AirdropDuration))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.LiquidityProviderCommission != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.LiquidityProviderCommission))
		i--
		dAtA[i] = 0x78
	}
	if len(m.LiquidityProviderAddress) > 0 {
		i -= len(m.LiquidityProviderAddress)
		copy(dAtA[i:], m.LiquidityProviderAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.LiquidityProviderAddress)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.ArchwayRewardFundsTransferAddress) > 0 {
		i -= len(m.ArchwayRewardFundsTransferAddress)
		copy(dAtA[i:], m.ArchwayRewardFundsTransferAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.ArchwayRewardFundsTransferAddress)))
		i--
		dAtA[i] = 0x6a
	}
	if m.MaximumThreshold != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.MaximumThreshold))
		i--
		dAtA[i] = 0x60
	}
	if m.RedemptionIntervalThreshold != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.RedemptionIntervalThreshold))
		i--
		dAtA[i] = 0x58
	}
	if m.RedemptionRateThreshold != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.RedemptionRateThreshold))
		i--
		dAtA[i] = 0x50
	}
	if len(m.RedemptionAddress) > 0 {
		i -= len(m.RedemptionAddress)
		copy(dAtA[i:], m.RedemptionAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.RedemptionAddress)))
		i--
		dAtA[i] = 0x4a
	}
	if m.RewardsWithdrawalInterval != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.RewardsWithdrawalInterval))
		i--
		dAtA[i] = 0x40
	}
	if m.RedemptionInterval != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.RedemptionInterval))
		i--
		dAtA[i] = 0x38
	}
	if m.LiquidStakeInterval != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.LiquidStakeInterval))
		i--
		dAtA[i] = 0x30
	}
	if len(m.LiquidityTokenAddress) > 0 {
		i -= len(m.LiquidityTokenAddress)
		copy(dAtA[i:], m.LiquidityTokenAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.LiquidityTokenAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if m.MinimumRewardAmount != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.MinimumRewardAmount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.RewardsAddress) > 0 {
		i -= len(m.RewardsAddress)
		copy(dAtA[i:], m.RewardsAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.RewardsAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BlockRewards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockRewards) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockRewards) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxGas != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.MaxGas))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.InflationRewards.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRewards(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Height != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TxRewards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxRewards) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxRewards) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeeRewards) > 0 {
		for iNdEx := len(m.FeeRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRewards(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Height != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if m.TxId != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.TxId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RewardsRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardsRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardsRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CalculatedTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CalculatedTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintRewards(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	if m.CalculatedHeight != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.CalculatedHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Rewards) > 0 {
		for iNdEx := len(m.Rewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRewards(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.RewardsAddress) > 0 {
		i -= len(m.RewardsAddress)
		copy(dAtA[i:], m.RewardsAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.RewardsAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintRewards(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FlatFee) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FlatFee) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FlatFee) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.FlatFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRewards(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintRewards(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRewards(dAtA []byte, offset int, v uint64) int {
	offset -= sovRewards(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.InflationRewardsRatio.Size()
	n += 1 + l + sovRewards(uint64(l))
	l = m.TxFeeRebateRatio.Size()
	n += 1 + l + sovRewards(uint64(l))
	if m.MaxWithdrawRecords != 0 {
		n += 1 + sovRewards(uint64(m.MaxWithdrawRecords))
	}
	return n
}

func (m *ContractMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = len(m.RewardsAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	if m.MinimumRewardAmount != 0 {
		n += 1 + sovRewards(uint64(m.MinimumRewardAmount))
	}
	l = len(m.LiquidityTokenAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	if m.LiquidStakeInterval != 0 {
		n += 1 + sovRewards(uint64(m.LiquidStakeInterval))
	}
	if m.RedemptionInterval != 0 {
		n += 1 + sovRewards(uint64(m.RedemptionInterval))
	}
	if m.RewardsWithdrawalInterval != 0 {
		n += 1 + sovRewards(uint64(m.RewardsWithdrawalInterval))
	}
	l = len(m.RedemptionAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	if m.RedemptionRateThreshold != 0 {
		n += 1 + sovRewards(uint64(m.RedemptionRateThreshold))
	}
	if m.RedemptionIntervalThreshold != 0 {
		n += 1 + sovRewards(uint64(m.RedemptionIntervalThreshold))
	}
	if m.MaximumThreshold != 0 {
		n += 1 + sovRewards(uint64(m.MaximumThreshold))
	}
	l = len(m.ArchwayRewardFundsTransferAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = len(m.LiquidityProviderAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	if m.LiquidityProviderCommission != 0 {
		n += 1 + sovRewards(uint64(m.LiquidityProviderCommission))
	}
	if m.AirdropDuration != 0 {
		n += 2 + sovRewards(uint64(m.AirdropDuration))
	}
	l = len(m.AirdropRecipientAddress)
	if l > 0 {
		n += 2 + l + sovRewards(uint64(l))
	}
	if m.AirdropVestingPeriod != 0 {
		n += 2 + sovRewards(uint64(m.AirdropVestingPeriod))
	}
	return n
}

func (m *BlockRewards) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovRewards(uint64(m.Height))
	}
	l = m.InflationRewards.Size()
	n += 1 + l + sovRewards(uint64(l))
	if m.MaxGas != 0 {
		n += 1 + sovRewards(uint64(m.MaxGas))
	}
	return n
}

func (m *TxRewards) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TxId != 0 {
		n += 1 + sovRewards(uint64(m.TxId))
	}
	if m.Height != 0 {
		n += 1 + sovRewards(uint64(m.Height))
	}
	if len(m.FeeRewards) > 0 {
		for _, e := range m.FeeRewards {
			l = e.Size()
			n += 1 + l + sovRewards(uint64(l))
		}
	}
	return n
}

func (m *RewardsRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovRewards(uint64(m.Id))
	}
	l = len(m.RewardsAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	if len(m.Rewards) > 0 {
		for _, e := range m.Rewards {
			l = e.Size()
			n += 1 + l + sovRewards(uint64(l))
		}
	}
	if m.CalculatedHeight != 0 {
		n += 1 + sovRewards(uint64(m.CalculatedHeight))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CalculatedTime)
	n += 1 + l + sovRewards(uint64(l))
	return n
}

func (m *FlatFee) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovRewards(uint64(l))
	}
	l = m.FlatFee.Size()
	n += 1 + l + sovRewards(uint64(l))
	return n
}

func sovRewards(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRewards(x uint64) (n int) {
	return sovRewards(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationRewardsRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InflationRewardsRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxFeeRebateRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TxFeeRebateRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxWithdrawRecords", wireType)
			}
			m.MaxWithdrawRecords = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxWithdrawRecords |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContractMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContractMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContractMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardsAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumRewardAmount", wireType)
			}
			m.MinimumRewardAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinimumRewardAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityTokenAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidityTokenAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidStakeInterval", wireType)
			}
			m.LiquidStakeInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidStakeInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedemptionInterval", wireType)
			}
			m.RedemptionInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RedemptionInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsWithdrawalInterval", wireType)
			}
			m.RewardsWithdrawalInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardsWithdrawalInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedemptionAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RedemptionAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedemptionRateThreshold", wireType)
			}
			m.RedemptionRateThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RedemptionRateThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedemptionIntervalThreshold", wireType)
			}
			m.RedemptionIntervalThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RedemptionIntervalThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaximumThreshold", wireType)
			}
			m.MaximumThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaximumThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArchwayRewardFundsTransferAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ArchwayRewardFundsTransferAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityProviderAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidityProviderAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityProviderCommission", wireType)
			}
			m.LiquidityProviderCommission = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidityProviderCommission |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirdropDuration", wireType)
			}
			m.AirdropDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AirdropDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirdropRecipientAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AirdropRecipientAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirdropVestingPeriod", wireType)
			}
			m.AirdropVestingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AirdropVestingPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockRewards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockRewards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockRewards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InflationRewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGas", wireType)
			}
			m.MaxGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxRewards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxRewards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxRewards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			m.TxId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeRewards = append(m.FeeRewards, types.Coin{})
			if err := m.FeeRewards[len(m.FeeRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RewardsRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardsRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardsRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardsAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rewards = append(m.Rewards, types.Coin{})
			if err := m.Rewards[len(m.Rewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CalculatedHeight", wireType)
			}
			m.CalculatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CalculatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CalculatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CalculatedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FlatFee) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FlatFee: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FlatFee: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlatFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRewards
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FlatFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRewards(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRewards
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRewards
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRewards
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRewards
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRewards
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRewards        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRewards          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRewards = fmt.Errorf("proto: unexpected end of group")
)
