version: "3"
services:
  stride1:
    image: stridezone:stride
    volumes:
      - ../state/stride1:/home/stride/.stride
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9091:9091"

  photo1:
    image: stridezone:photo
  #  build:
  #    context: /media/swordfish/SeaConda1/photov1/photo12/Photosynthesis-Dorahacks-web3-competition-winner/photosynthesisv4/photosynthesis-main/archway-main
  #   command: start --home /home/photo/.photod --log_level trace --log_format json
    #ports:
     # - 40000:40000
     # - 9090:9090
     # - 26657:26657
    volumes:
     # - /media/swordfish/SeaConda1/photov1/photo12/Photosynthesis-Dorahacks-web3-competition-winner/photosynthesisv4/photosynthesis-main/archway-main/contrib/localnet:/opt:z
     # - /media/swordfish/SeaConda1/photov1/photo12/Photosynthesis-Dorahacks-web3-competition-winner/photosynthesisv4/photosynthesis-main/archway-main/contracts:/contracts:z
      - ./state/photo1:/home/photo/.photod
    #working_dir: /opt
    #ports:
    #  - "26058:26657"
    #  - "1310:1319"
    #  - "9050:9092"

  hermes:
    image: stridezone:hermes
    volumes:
      - ~/.hermes:/home/hermes/.hermes
      - ../state/hermes/config.toml:/home/hermes/.hermes/config.toml
    restart: always

  relayer:
    image: stridezone:relayer
    volumes:
      - ../state/relayer:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-host" ]
