global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
chains:
    evmos:
        type: cosmos
        value:
            key-directory: /home/relayer/.relayer/keys/evmos_9001-2
            key: rly7
            chain-id: evmos_9001-2
            rpc-addr: http://evmos1:26657
            account-prefix: evmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01aevmos
            min-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs:
                - ethermint
            coin-type: 60
            broadcast-mode: batch
    gaia:
        type: cosmos
        value:
            key-directory: /home/relayer/.relayer/keys/GAIA
            key: rly2
            chain-id: GAIA
            rpc-addr: http://gaia1:26657
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uatom
            min-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            broadcast-mode: batch
    host:
        type: cosmos
        value:
            key-directory: /home/relayer/.relayer/keys/HOST
            key: rly6
            chain-id: HOST
            rpc-addr: http://host1:26657
            account-prefix: stride
            keyring-backend: test
            gas-adjustment: 1.3
            gas-prices: 0.01uwalk
            min-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            broadcast-mode: batch
    juno:
        type: cosmos
        value:
            key-directory: /home/relayer/.relayer/keys/JUNO
            key: rly3
            chain-id: JUNO
            rpc-addr: http://juno1:26657
            account-prefix: juno
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ujuno
            min-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            broadcast-mode: batch
    osmo:
        type: cosmos
        value:
            key-directory: /home/relayer/.relayer/keys/OSMO
            key: rly4
            chain-id: OSMO
            rpc-addr: http://osmo1:26657
            account-prefix: osmo
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uosmo
            min-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            broadcast-mode: batch
    photo:
        type: cosmos
        value:
            key-directory: /home/relayer/.relayer/keys/localnet
            key: rly0
            chain-id: localnet
            rpc-addr: http://photo1:26657
            account-prefix: archway
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uarch
            min-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            broadcast-mode: batch
    stars:
        type: cosmos
        value:
            key-directory: /home/relayer/.relayer/keys/STARS
            key: rly5
            chain-id: STARS
            rpc-addr: http://stars1:26657
            account-prefix: stars
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ustars
            min-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            broadcast-mode: batch
    stride:
        type: cosmos
        value:
            key-directory: /home/relayer/.relayer/keys/STRIDE
            key: rly1
            chain-id: STRIDE
            rpc-addr: http://stride1:26657
            account-prefix: stride
            keyring-backend: test
            gas-adjustment: 1.3
            gas-prices: 0.01ustrd
            min-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            broadcast-mode: batch
paths:
    stride-evmos:
        src:
            chain-id: STRIDE
        dst:
            chain-id: evmos_9001-2
        src-channel-filter:
            rule: ""
            channel-list: []
    stride-gaia:
        src:
            chain-id: STRIDE
            client-id: 07-tendermint-0
            connection-id: connection-0
        dst:
            chain-id: GAIA
            client-id: 07-tendermint-0
            connection-id: connection-0
        src-channel-filter:
            rule: ""
            channel-list: []
    stride-host:
        src:
            chain-id: STRIDE
        dst:
            chain-id: HOST
        src-channel-filter:
            rule: ""
            channel-list: []
    stride-juno:
        src:
            chain-id: STRIDE
        dst:
            chain-id: JUNO
        src-channel-filter:
            rule: ""
            channel-list: []
    stride-osmo:
        src:
            chain-id: STRIDE
        dst:
            chain-id: OSMO
        src-channel-filter:
            rule: ""
            channel-list: []
    stride-photo:
        src:
            chain-id: STRIDE
        dst:
            chain-id: localnet
        src-channel-filter:
            rule: ""
            channel-list: []
    stride-stars:
        src:
            chain-id: STRIDE
        dst:
            chain-id: STARS
        src-channel-filter:
            rule: ""
            channel-list: []
