[package]
name = "arch-mocks"
version = "0.1.0-dev"
edition = "2018"


[package.metadata.docs.rs]
features = ["staking"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "0.16.1" }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.1"
