global:
  api-listen-addr: :5183
  timeout: 60s
  memo: ""
  light-cache-size: 20
chains:
  stride:
    type: cosmos
    value:
      key: rly1
      chain-id: STRIDE_CHAIN_ID
      rpc-addr: http://stride1:26657
      account-prefix: stride
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.01ustrd
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  host:
    type: cosmos
    value:
      key: rly0
      chain-id: localnet
      rpc-addr: http://photo1:26657
      account-prefix: archway
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 100uatom
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
paths:
  stride-host:
    src:
      chain-id: stride
    dst:
      chain-id: localnet
    src-channel-filter:
      rule: ""
      channel-list: []
